language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script:
  - nosetests
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database watchapp;' -U postgres
  - python manage.py syncdb --noinput
notifications:
  email:
    recipients:
      - l.salamanca10@uniandes.edu.co
    on_success: always
    on_failure: never
